apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml

namespace: default

commonLabels:
  app.kubernetes.io/name: nginx-example
  app.kubernetes.io/part-of: homelab
  environment: dev